buildscript {
    ext {
        compose_ui_version = '1.5.4'
        kotlin_version = '1.9.10'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // ✅ Add here
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1' // latest available (unstable)

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // ✅ And here
    }
}
