// Top-level build.gradle.kts

buildscript {
    ext.kotlin_version = '2.0.20'
    repositories {
        google()
        mavenCentral()
    //    maven { url = uri("https://jitpack.io") }
     //   jcenter()
    }

    dependencies {
        classpath("com.autonomousapps:dependency-analysis-gradle-plugin:3.5.1") // Replace with the latest version
        classpath('com.android.tools.build:gradle:8.7.3')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.6'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
plugins {
    id("com.autonomousapps.dependency-analysis") version "3.5.1" apply false
} // Use the latest version and apply false
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
       // maven { url = uri("https://jitpack.io") }
      //  jcenter()
    }
    configurations.configureEach {
        resolutionStrategy {
            // Increase timeout for dependency resolution
            cacheChangingModulesFor 1, 'seconds'
            cacheDynamicVersionsFor 1, 'seconds'
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
